name: Dep Job example

on: [workflow_dispatch]

jobs:
  runs-on: ubuntu-latest
  job1:
    steps:
      - name: stepA
        run: echo "Hello world"
  job2:
    steps:
      - name: stepB
        run: echo "Hello Mars"