name: Webhook

on: 
  repository_dispatch:
    types: [test_result]

jobs:
  respond-to-dispatch: #name
    runs-on: ubuntu-latest
    steps:
      -name: Checkout repo
      uses: actions/checkout@v2
      -name: Run a script
      run: echo "Event of type: $GITHUB_EVENT_NAME"